Repository EricssonResearch/arms, pull requests merged in 2018-11, with the labels that each got.

#32 Making the RAPID API accessible via socket communication
  other/abb/server.mod
  other/abb/tests/test_server.py
Labels: 10, feature, language: Python, language: RAPID

#35 Issue 15 - getTranslation()
  arms/arduino/arduino.py
  arms/arduino/gripperPos.txt
Labels: Arduino class, language: Python

#38 Socket Client
  arms/misc/__init__.py
  arms/misc/socket.py
  arms/utils/log.py
  requirements.txt
  tests/unit/test_socket.py
Labels: feature, language: Python
